//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ax.SRM.WP.POMM0030_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.seoyon.com/mm/scm", ConfigurationName="POMM0030_Service.POMM0030_SCM_SO")]
    public interface POMM0030_SCM_SO {
        
        // CODEGEN: POMM0030_SCM_SO 작업이 RPC 또는 문서 래핑이 아니므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SOResponse POMM0030_SCM_SO(Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.seoyon.com/mm/scm")]
    public partial class DT_POMM0030_SCM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReqHeader reqHeaderField;
        
        private DT_POMM0030_SCMZMMS0200[] zMMS0200Field;
        
        private DT_POMM0030_SCMZMMS0202[] zMMS0202Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ReqHeader ReqHeader {
            get {
                return this.reqHeaderField;
            }
            set {
                this.reqHeaderField = value;
                this.RaisePropertyChanged("ReqHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZMMS0200", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_POMM0030_SCMZMMS0200[] ZMMS0200 {
            get {
                return this.zMMS0200Field;
            }
            set {
                this.zMMS0200Field = value;
                this.RaisePropertyChanged("ZMMS0200");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZMMS0202", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_POMM0030_SCMZMMS0202[] ZMMS0202 {
            get {
                return this.zMMS0202Field;
            }
            set {
                this.zMMS0202Field = value;
                this.RaisePropertyChanged("ZMMS0202");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.seoyon.com/mm/Common")]
    public partial class ReqHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zRoutingCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string zRoutingCd {
            get {
                return this.zRoutingCdField;
            }
            set {
                this.zRoutingCdField = value;
                this.RaisePropertyChanged("zRoutingCd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.seoyon.com/mm/Common")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zResultCdField;
        
        private string zResultMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string zResultCd {
            get {
                return this.zResultCdField;
            }
            set {
                this.zResultCdField = value;
                this.RaisePropertyChanged("zResultCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string zResultMsg {
            get {
                return this.zResultMsgField;
            }
            set {
                this.zResultMsgField = value;
                this.RaisePropertyChanged("zResultMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.seoyon.com/mm/scm")]
    public partial class DT_POMM0030_SCM_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResHeader resHeaderField;
        
        private DT_POMM0030_SCM_responseZMMS0200[] zMMS0200Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResHeader ResHeader {
            get {
                return this.resHeaderField;
            }
            set {
                this.resHeaderField = value;
                this.RaisePropertyChanged("ResHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZMMS0200", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_POMM0030_SCM_responseZMMS0200[] ZMMS0200 {
            get {
                return this.zMMS0200Field;
            }
            set {
                this.zMMS0200Field = value;
                this.RaisePropertyChanged("ZMMS0200");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.seoyon.com/mm/scm")]
    public partial class DT_POMM0030_SCM_responseZMMS0200 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUKRSField;
        
        private string wERKSField;
        
        private string dELI_NOTEField;
        
        private string dELI_NOTE_CNTField;
        
        private string iF_DATEField;
        
        private string iF_TIMEField;
        
        private string zRSLT_SAPField;
        
        private string zMSG_SAPField;
        
        private string zDATE_SAPField;
        
        private string zTIME_SAPField;
        
        private string zDATE_POField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DELI_NOTE {
            get {
                return this.dELI_NOTEField;
            }
            set {
                this.dELI_NOTEField = value;
                this.RaisePropertyChanged("DELI_NOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DELI_NOTE_CNT {
            get {
                return this.dELI_NOTE_CNTField;
            }
            set {
                this.dELI_NOTE_CNTField = value;
                this.RaisePropertyChanged("DELI_NOTE_CNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IF_DATE {
            get {
                return this.iF_DATEField;
            }
            set {
                this.iF_DATEField = value;
                this.RaisePropertyChanged("IF_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IF_TIME {
            get {
                return this.iF_TIMEField;
            }
            set {
                this.iF_TIMEField = value;
                this.RaisePropertyChanged("IF_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZRSLT_SAP {
            get {
                return this.zRSLT_SAPField;
            }
            set {
                this.zRSLT_SAPField = value;
                this.RaisePropertyChanged("ZRSLT_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZMSG_SAP {
            get {
                return this.zMSG_SAPField;
            }
            set {
                this.zMSG_SAPField = value;
                this.RaisePropertyChanged("ZMSG_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZDATE_SAP {
            get {
                return this.zDATE_SAPField;
            }
            set {
                this.zDATE_SAPField = value;
                this.RaisePropertyChanged("ZDATE_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZTIME_SAP {
            get {
                return this.zTIME_SAPField;
            }
            set {
                this.zTIME_SAPField = value;
                this.RaisePropertyChanged("ZTIME_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZDATE_PO {
            get {
                return this.zDATE_POField;
            }
            set {
                this.zDATE_POField = value;
                this.RaisePropertyChanged("ZDATE_PO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.seoyon.com/mm/scm")]
    public partial class DT_POMM0030_SCMZMMS0200 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUKRSField;
        
        private string wERKSField;
        
        private string dELI_NOTEField;
        
        private string dELI_NOTE_CNTField;
        
        private string iF_DATEField;
        
        private string iF_TIMEField;
        
        private string lFDATField;
        
        private string cRDATField;
        
        private string lIFNRField;
        
        private string eKORGField;
        
        private string dELI_TYPEField;
        
        private string dELI_STATField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string mATNRField;
        
        private string lGORTField;
        
        private string lFIMGField;
        
        private string mEINSField;
        
        private string bARCODEField;
        
        private string nATION_CDField;
        
        private string lOT_NOField;
        
        private string vEND_LOTNOField;
        
        private string cHANGE_NOTEField;
        
        private string zRSLT_SAPField;
        
        private string zMSG_SAPField;
        
        private string zDATE_SAPField;
        
        private string zTIME_SAPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DELI_NOTE {
            get {
                return this.dELI_NOTEField;
            }
            set {
                this.dELI_NOTEField = value;
                this.RaisePropertyChanged("DELI_NOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DELI_NOTE_CNT {
            get {
                return this.dELI_NOTE_CNTField;
            }
            set {
                this.dELI_NOTE_CNTField = value;
                this.RaisePropertyChanged("DELI_NOTE_CNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IF_DATE {
            get {
                return this.iF_DATEField;
            }
            set {
                this.iF_DATEField = value;
                this.RaisePropertyChanged("IF_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IF_TIME {
            get {
                return this.iF_TIMEField;
            }
            set {
                this.iF_TIMEField = value;
                this.RaisePropertyChanged("IF_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string LFDAT {
            get {
                return this.lFDATField;
            }
            set {
                this.lFDATField = value;
                this.RaisePropertyChanged("LFDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CRDAT {
            get {
                return this.cRDATField;
            }
            set {
                this.cRDATField = value;
                this.RaisePropertyChanged("CRDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string EKORG {
            get {
                return this.eKORGField;
            }
            set {
                this.eKORGField = value;
                this.RaisePropertyChanged("EKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DELI_TYPE {
            get {
                return this.dELI_TYPEField;
            }
            set {
                this.dELI_TYPEField = value;
                this.RaisePropertyChanged("DELI_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DELI_STAT {
            get {
                return this.dELI_STATField;
            }
            set {
                this.dELI_STATField = value;
                this.RaisePropertyChanged("DELI_STAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
                this.RaisePropertyChanged("EBELP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
                this.RaisePropertyChanged("LGORT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string LFIMG {
            get {
                return this.lFIMGField;
            }
            set {
                this.lFIMGField = value;
                this.RaisePropertyChanged("LFIMG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string BARCODE {
            get {
                return this.bARCODEField;
            }
            set {
                this.bARCODEField = value;
                this.RaisePropertyChanged("BARCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string NATION_CD {
            get {
                return this.nATION_CDField;
            }
            set {
                this.nATION_CDField = value;
                this.RaisePropertyChanged("NATION_CD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string LOT_NO {
            get {
                return this.lOT_NOField;
            }
            set {
                this.lOT_NOField = value;
                this.RaisePropertyChanged("LOT_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string VEND_LOTNO {
            get {
                return this.vEND_LOTNOField;
            }
            set {
                this.vEND_LOTNOField = value;
                this.RaisePropertyChanged("VEND_LOTNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CHANGE_NOTE {
            get {
                return this.cHANGE_NOTEField;
            }
            set {
                this.cHANGE_NOTEField = value;
                this.RaisePropertyChanged("CHANGE_NOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string ZRSLT_SAP {
            get {
                return this.zRSLT_SAPField;
            }
            set {
                this.zRSLT_SAPField = value;
                this.RaisePropertyChanged("ZRSLT_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string ZMSG_SAP {
            get {
                return this.zMSG_SAPField;
            }
            set {
                this.zMSG_SAPField = value;
                this.RaisePropertyChanged("ZMSG_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ZDATE_SAP {
            get {
                return this.zDATE_SAPField;
            }
            set {
                this.zDATE_SAPField = value;
                this.RaisePropertyChanged("ZDATE_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ZTIME_SAP {
            get {
                return this.zTIME_SAPField;
            }
            set {
                this.zTIME_SAPField = value;
                this.RaisePropertyChanged("ZTIME_SAP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.seoyon.com/mm/scm")]
    public partial class DT_POMM0030_SCMZMMS0202 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUKRSField;
        
        private string wERKSField;
        
        private string dELI_NOTEField;
        
        private string dELI_NOTE_CNTField;
        
        private string bOX_BARCODEField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string mATNRField;
        
        private string bARCODEField;
        
        private string sEQ_NOField;
        
        private string iDENTI_NOField;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string zRSLT_SAPField;
        
        private string zMSG_SAPField;
        
        private string zDATE_SAPField;
        
        private string zTIME_SAPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DELI_NOTE {
            get {
                return this.dELI_NOTEField;
            }
            set {
                this.dELI_NOTEField = value;
                this.RaisePropertyChanged("DELI_NOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DELI_NOTE_CNT {
            get {
                return this.dELI_NOTE_CNTField;
            }
            set {
                this.dELI_NOTE_CNTField = value;
                this.RaisePropertyChanged("DELI_NOTE_CNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BOX_BARCODE {
            get {
                return this.bOX_BARCODEField;
            }
            set {
                this.bOX_BARCODEField = value;
                this.RaisePropertyChanged("BOX_BARCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
                this.RaisePropertyChanged("EBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
                this.RaisePropertyChanged("EBELP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string BARCODE {
            get {
                return this.bARCODEField;
            }
            set {
                this.bARCODEField = value;
                this.RaisePropertyChanged("BARCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SEQ_NO {
            get {
                return this.sEQ_NOField;
            }
            set {
                this.sEQ_NOField = value;
                this.RaisePropertyChanged("SEQ_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IDENTI_NO {
            get {
                return this.iDENTI_NOField;
            }
            set {
                this.iDENTI_NOField = value;
                this.RaisePropertyChanged("IDENTI_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
                this.RaisePropertyChanged("MENGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZRSLT_SAP {
            get {
                return this.zRSLT_SAPField;
            }
            set {
                this.zRSLT_SAPField = value;
                this.RaisePropertyChanged("ZRSLT_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ZMSG_SAP {
            get {
                return this.zMSG_SAPField;
            }
            set {
                this.zMSG_SAPField = value;
                this.RaisePropertyChanged("ZMSG_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ZDATE_SAP {
            get {
                return this.zDATE_SAPField;
            }
            set {
                this.zDATE_SAPField = value;
                this.RaisePropertyChanged("ZDATE_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ZTIME_SAP {
            get {
                return this.zTIME_SAPField;
            }
            set {
                this.zTIME_SAPField = value;
                this.RaisePropertyChanged("ZTIME_SAP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POMM0030_SCM_SORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.seoyon.com/mm/scm", Order=0)]
        public Ax.SRM.WP.POMM0030_Service.DT_POMM0030_SCM MT_POMM0030_SCM;
        
        public POMM0030_SCM_SORequest() {
        }
        
        public POMM0030_SCM_SORequest(Ax.SRM.WP.POMM0030_Service.DT_POMM0030_SCM MT_POMM0030_SCM) {
            this.MT_POMM0030_SCM = MT_POMM0030_SCM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POMM0030_SCM_SOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.seoyon.com/mm/scm", Order=0)]
        public Ax.SRM.WP.POMM0030_Service.DT_POMM0030_SCM_response MT_POMM0030_SCM_response;
        
        public POMM0030_SCM_SOResponse() {
        }
        
        public POMM0030_SCM_SOResponse(Ax.SRM.WP.POMM0030_Service.DT_POMM0030_SCM_response MT_POMM0030_SCM_response) {
            this.MT_POMM0030_SCM_response = MT_POMM0030_SCM_response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface POMM0030_SCM_SOChannel : Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class POMM0030_SCM_SOClient : System.ServiceModel.ClientBase<Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SO>, Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SO {
        
        public POMM0030_SCM_SOClient() {
        }
        
        public POMM0030_SCM_SOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public POMM0030_SCM_SOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POMM0030_SCM_SOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POMM0030_SCM_SOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SOResponse Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SO.POMM0030_SCM_SO(Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SORequest request) {
            return base.Channel.POMM0030_SCM_SO(request);
        }
        
        public Ax.SRM.WP.POMM0030_Service.DT_POMM0030_SCM_response POMM0030_SCM_SO(Ax.SRM.WP.POMM0030_Service.DT_POMM0030_SCM MT_POMM0030_SCM) {
            Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SORequest inValue = new Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SORequest();
            inValue.MT_POMM0030_SCM = MT_POMM0030_SCM;
            Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SOResponse retVal = ((Ax.SRM.WP.POMM0030_Service.POMM0030_SCM_SO)(this)).POMM0030_SCM_SO(inValue);
            return retVal.MT_POMM0030_SCM_response;
        }
    }
}
